### ISSUE TITLE
Based on which astrology?

### ISSUE THREAD

**Issue by manikandancode** [alexkdeveloper/zodiac#3]
Need some explanation

**Comment by alexkdeveloper** [comment]
The application uses the [Kerykeion library](https://pypi.org/project/kerykeion/) to compile horoscopes. 
Most likely, the classical Western system of astrology is used. 
There is no way to create an interpretation of horoscopes in the library.

**Comment by manikandancode** [comment]
Thanks. Add these details in [README.md](https://github.com/alexkdeveloper/zodiac#readme) to help others.
